### ISSUE TITLE
Notification height for non square images

### ISSUE THREAD

**Issue by czaplicki** [phillbush/xnotify#10]
Hey again, noticed that height of notification is independent of the image height.
So it leaves a lot room at the top and bottom,
any chance you could take the image height in consideration when calculating the notifications height?
![image](https://user-images.githubusercontent.com/3816549/106741762-71d78800-661c-11eb-976a-798fc2736917.png)

**Comment by phillbush** [comment]
This should be fixed now.
With the last commit the height is adjusted to the image height (plus the top and bottom padding).

Can you check if this work?

**Comment by czaplicki** [comment]
Works perfectly, thank you!
