### ISSUE TITLE
image only notification

### ISSUE THREAD

**Issue by vredesbyyrd** [phillbush/xnotify#16]
Hi, love this tool, thanks for sharing it! 

I recently updated `xnotify` for the first time in months, I was on version `20201025-1`. On that version I was doing image only notifications for use with `mpd`, the goal was to display `300x300` album art. On updating to the latest master that behavior no longer works.  

**config:**
```


static struct Config config = {
	/* fonts, separate different fonts with comma */
	.titlefont = "monospace:size=9:style=bold",
	.bodyfont = "monospace:size=9",

	/* colors */
	.background_color = "#000000",
	.foreground_color = "#FFFFFF",
	.border_color = "#3465a4",

	/* geometry and gravity (see the manual) */
	.geometryspec = "0x0+0+0",
	.gravityspec = "NE",

	/* size of border, gaps and image (in pixels) */
	.border_pixels = 2,
	.gap_pixels = 7,
	.image_pixels = 0,     /* if 0, the image will fit the notification */
	.leading_pixels = 5,    /* space between title and body texts */
	.padding_pixels = 8,   /* space around content */
	.max_height = 300,      /* maximum height of a notification, after text wrapping */

	/* text alignment, set to LeftAlignment, CenterAlignment or RightAlignment */
	.alignment = RightAlignment,

	/* set to nonzero to shrink notification width to its content size */
	.shrink = 0,

	/* whether to wrap text */
	.wrap = 0,

	/* time, in seconds, for a notification to stay alive */
	.sec = 10,

	/* mouse button that makes xnotify prints a notification's CMD: */
	.actionbutton = Button3
};
/* string to be replaced by truncated text, should be a single unicode character */
#define ELLIPSIS "…" 
```

I write to a fifo... 
```
# create a variable pointing to the pipe
export XNOTIFY_FIFO="$HOME/.cache/xnotify$DISPLAY.fifo"
rm -f $XNOTIFY_FIFO
mkfifo $XNOTIFY_FIFO
xnotify -o -G NE -g 300x300-5+30 -s 3 0<>$XNOTIFY_FIFO 

```
Before updating i found that just writing an image + blank space resulted in a perfectly square "album art" notification.

`printf 'IMG:/home/clu/.cache/beet_mpd/1433_big.jpg\t \n' > $XNOTIFY_FIFO` 

On latest master no matter what I try with the config the image always displays as a small thumbnail, eg... 

![Screenshot from 2021-05-09 16-49-55](https://user-images.githubusercontent.com/22080838/117588373-82e6d800-b0e8-11eb-8686-0c792ed7852a.png) 

On version `20201025-1` 

![Screenshot from 2021-05-09 17-09-21](https://user-images.githubusercontent.com/22080838/117588579-cb52c580-b0e9-11eb-83d5-9018ccb01494.png)

Any thoughts? If this is no longer possible, nbg, I could just make a more standard style notification that includes text with a smaller image. 

Thanks for your time!

**Comment by vredesbyyrd** [comment]
Right on :)  Thank you!

**Comment by phillbush** [comment]
Done!  
Now you do not need the `IMG:…` + blank space hack to create an image-only notification, now the IMG string alone suffices.

**Comment by vredesbyyrd** [comment]
That was quick, thank you!  

> Now you do not need the IMG:… + blank space hack to create an image-only notification, now the IMG string alone suffices. 

Awesome :) 

I'm still running into a strange bug. No matter what I try the cover image remains small, exactly as shown in my first screenshot. This is my test command...  

`printf 'IMG:/home/clu/.cache/beet_mpd/182_big.jpg' | xnotify -o -G NE -g 300x300-5+30 -s 3` 

The source image is exactly 300x300. At the moment I cannot think of anything that would be causing this behavior, but i'll play around and see if I cant find any hints.

**Comment by phillbush** [comment]
That's strange, it's working here.
Did you updated your `config.h`? If you have not set `.image_pixels` to `0` the image will still have constant small size.

**Comment by vredesbyyrd** [comment]
Agree its a strange one. I did update `config.h`, `.image_pixels` is set to `0`
