### ISSUE TITLE
Left space padding by default too big, issue?

### ISSUE THREAD

**Issue by OzPineapple** [phillbush/xnotify#17]
I also tried to set padding to zero but it dosen't make any diference. I have a bad setting? On the gif image from the repo looks direfent.
![image](https://user-images.githubusercontent.com/35550219/119061692-8dcc2300-b99a-11eb-8c3b-e85f7c3d7519.png)

**Comment by phillbush** [comment]
I could not replicate your issue.
What text are you passing for xnotify to display?

**Comment by OzPineapple** [comment]
I made a script for unicode, [unicode-insert](https://github.com/OzPineapple/unicode-insert) that send the text to xnotify
It happends anyway
![image](https://user-images.githubusercontent.com/35550219/119741347-22c39600-be4b-11eb-9c56-9a9ae8bf08d8.png)
```
xnotify.title.font: Mono-15
xnotify.body.font: Mono-12
xnotify.border: #00BB55
xnotify.gravity: SW
xnotify.wrap: true
```
This is my Xresources file

**Comment by phillbush** [comment]
The last commit fixes the issue.

**Comment by OzPineapple** [comment]
Thanx UwU
