### ISSUE TITLE
Not working with tiramisu

### ISSUE THREAD

**Issue by CarlosLoboxyz** [phillbush/xnotify#18]
It looks like tiramisu only accepts a paremeter `-o` and the exaple show in the Readme is no longer working, i tried this:

```bash
$ xnotify 0<>$XNOTIFY_FIFO &
$ tiramisu | jq --raw-output --unbuffered '.summary + "\t" + .body' > $XNOTIFY_FIFO &
```

The output:
```bash
(process:7455): GLib-CRITICAL **: 12:24:41.831: g_variant_unref: assertion 'value != NULL' failed
notify-send

0
Hello World
This is a test
#actions
,urgency=
-1
```

and the notification is no showing up, any idea how to make it work?

**Comment by phillbush** [comment]
I do not have tiramisu installed, because I do not have dbus.
But, I think you can do that.

```
$ xnotify 0<>$XNOTIFY_FIFO &
$ tiramisu -o '#summary\t
#body' > $XNOTIFY_FIFO &
```

Replace `\t` by a literal tab.

I'll install tiramisu later to check it.

**Comment by CarlosLoboxyz** [comment]
It works, thanks. 

Maybe it would be a good idea to update the readme to include the above example
