### ISSUE TITLE
Include example in readme and wiki

### ISSUE THREAD

**Issue by CarlosLoboxyz** [phillbush/xnotify#19]
```sh
#!/bin/sh

# Check if process already exist
pgrep xnotify && exit 1
pgrep tiramisu && exit 1

# Create notification fifo
export XNOTIFY_FIFO="/tmp/xnotify$DISPLAY.fifo"
rm -f $XNOTIFY_FIFO
mkfifo $XNOTIFY_FIFO
xnotify 0<>$XNOTIFY_FIFO &

# Listen  to dbus
tiramisu -o "$(printf '#source\t#summary: #body')" > $XNOTIFY_FIFO &
```

a simple script to run notifications for a complete desktop experience

![image](https://user-images.githubusercontent.com/86011416/124520324-1cb1c500-ddba-11eb-8872-84799b4ebdf0.png)

**Comment by phillbush** [comment]
The line exporting the variable `XNOTIFY_FIFO` has no effect when running from this script.
This line should be on a rc file such as `~/.xinitrc` for that variable to be exported to (and be accessed by) other scripts and programs.
I think that a rc file is the best place to call xnotify.

**Comment by CarlosLoboxyz** [comment]
you right, i think the final result could be something like this:

`export XNOTIFY_FIFO="/tmp/xnotify$DISPLAY.fifo"` inside `.xinitrc` or `.bashrc`

```sh
#!/bin/sh

pgrep xnotify && exit 1
pgrep tiramisu && exit 1

# Create notification fifo
rm -f $XNOTIFY_FIFO
mkfifo $XNOTIFY_FIFO
xnotify 0<>$XNOTIFY_FIFO &

# Listen  to dbus
tiramisu -o "$(printf '#source\t#summary: #body')" > $XNOTIFY_FIFO &
```
