### ISSUE TITLE
How to run a command inside CMD?

### ISSUE THREAD

**Issue by CarlosLoboxyz** [phillbush/xnotify#20]
I'm creating an script for screenshot, and i want to be able to open my image viewer whenever i click in the notification dialog, the CMD flag returns the given value to stdout, how can i execute this command while running the notification daemon?

Example:
```sh
xnotify -b 1 0<>$XNOTIFY_FIFO
```

```sh
printf 'CMD:sxiv "$IMAGE"\tScreenshot saved to:\t$LOCATION'
```
![image](https://user-images.githubusercontent.com/86011416/124530989-88f0f080-dddb-11eb-9983-5cb5c60ab769.png)

clicking in the notification returns this:
![image](https://user-images.githubusercontent.com/86011416/124530864-4f1fea00-dddb-11eb-8ebb-5e37815e9fd2.png)
Now i just need to execute w/o killing the daemon

Side note: it's there any way to change the color of the body line? to make it blue like a url?

**Comment by phillbush** [comment]
Pipe the output of xnotify to sh, so the command is run by the shell.

```
xnotify -b 1 0<>$XNOTIFY_FIFO | sh &
```

On the color: the color is applied to all the text (both title and body).

BTW, you can use the following to display the image on the notification:

```
printf 'IMG:%s\tCMD:%s\t%s\t%s\n' "$IMAGE" "sxiv \"$IMAGE\"" "Screenshot saved to" "$LOCATION"
```

**Comment by CarlosLoboxyz** [comment]
`xnotify -b 1 0<>$XNOTIFY_FIFO | sh &`

does not work, the image viewer is not being executed, i also tried using 

`eval "$(xnotify 0<>$XNOTIFY_FIFO)"` 

and 

`xnotify -b 1 0<>$XNOTIFY_FIFO | while IFS= read -r cmd; do "$cmd"; done`  as show in [here](https://unix.stackexchange.com/questions/318401/execute-stdout-results) 

another idea?

**Comment by phillbush** [comment]
Try again to pipe to sh as I said. My last commit will fix that (the output of xnotify was not flushed, so sh did not have access to it when the user clicked on the notification).

**Comment by CarlosLoboxyz** [comment]
It works, thanks, and also thanks for sharing this amazing tool :)
