### ISSUE TITLE
Vertical top alignment of text area?

### ISSUE THREAD

**Issue by z0noxz** [phillbush/xnotify#22]
The text area is vertically centered by default if an image is larger than the height of the text area. Would you be interested in a PR that adds a boolean flag that either sets the text area vertically centered or aligned to the top (see image)?

I just made a minor change at line 844 to achieve this (here without any flag).

```
if (item->textw > 0) {
   XCopyArea(dpy, textpixmap, item->pixmap, dc.gc, 0, 0, item->textw, texth,
      config.padding_pixels + (image && item->imgw > 0 ? item->imgw + config.padding_pixels : 0),
      config.padding_pixels);
```

![image](https://user-images.githubusercontent.com/20256795/128740288-da8ea0c5-ddee-444a-a67f-8ae565764ea4.png)

**Comment by phillbush** [comment]
That's a nice feature and simple to implement.  
I'll merge the PR.
