### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by vredesbyyrd** [phillbush/xnotify#25]
Hi, 

Part of `xnotify` beauty is its simplicity, and I am unsure if supporting `svg` icons works against that, but I have noticed that a lot of common icon "themes" are using svgs. One nice thing about `svg` is they can easily be recolored on the fly.  

Just a suggestion.

**Comment by vredesbyyrd** [comment]
I missed this notification, sorry.  

Yeah I suspected the only option, or default one would be cairo which I totally understand not wanting to add as a dependency. I never heard of `nanosvg`, looks promising at least.

**Comment by sammycage** [comment]
You can try LunaSVG

LunaSVG is a standalone SVG rendering library in C++
It supports complex markers, gradients, patterns and more.

For more details :

https://github.com/sammycage/lunasvg

**Comment by phillbush** [comment]
A recent version of imlib2 added support to svg images via librsvg.
Thus xnotify now supports svg too.

**Comment by vredesbyyrd** [comment]
Nice! Thanks for the heads up.
