### ISSUE TITLE
FEATURE: add UTF8 support

### ISSUE THREAD

**Issue by BeyondMagic** [phillbush/xnotify#28]
xnotify can't read UTF8 characters, example with Japanese:

![image](https://user-images.githubusercontent.com/51831435/141829460-bdbbf9c6-fd71-4354-9699-c3638a8b138d.png)

**Comment by phillbush** [comment]
xnotify support UTF8 fonts and font fallback, as you can see on the image.

![font](https://user-images.githubusercontent.com/63266536/141831772-2e01d44f-2470-4fd3-b34e-947f71982adb.png)

Change your .Xresources, adding the following line:

```
xnotify*font: PRIMARY_FONT,SECONDARY_FONT,CJK_FONT
```

Replace the names of your primary, secondary, etc, and CJK font with the names listed by the `fc-list(1)` program.

**Comment by BeyondMagic** [comment]
I see, my bad, thanks for the amazing program and fast response.
