### ISSUE TITLE
Updates system

### ISSUE THREAD

**Issue by tuxliban** [phillbush/xnotify#3]
Hello, first of all I want to congratulate you on your program.
The question I have is how could I make the notification of available updates for my system show them to me in a single notification and not split it into a notification for each available package?
The manual says that to show notifications with some image, I have to configure something like this:

```
printf 'IMG:/path/to/file.png\tThis is a notification\n' > $XNOTIFY_FIFO
```

This is my script:

```
lista=$(xbps-install -nuM | awk '{print $1, $2}' )
lista2=$(xbps-install -nuM | awk '{print $1, $2}' | tail -n 12 )
updates=$(xbps-install -nuM | wc -l)

~/Datos/Git/scripts/varios/dunst_sound.sh
if [ "$updates" -eq 1 ]; then
        printf "IMG:/home/skynet/Datos/Git_Hub/Void_Linux/otros/icons/status/package-upgrade.png\tHay una actualización disponible\t$updates\n" > $XNOTIFY_FIFO
elif [ "$updates" -le 10 ] && [ "$updates" -gt 1 ]; then
        printf "IMG:/home/skynet/Datos/Git_Hub/Void_Linux/otros/icons/status/package-upgrade.png\tHay $updates actualizaciones disponibles\t$lista\n" > $XNOTIFY_FIFO
elif [ "$updates" -gt 11 ]; then
        printf "IMG:/home/skynet/Datos/Git_Hub/Void_Linux/otros/icons/status/package-upgrade.png\tHay $updates actualizaciones disponibles\t$lista2\n" > $XNOTIFY_FIFO
else
        echo ""
fi
```

When I have updates available, are divided in this way:
![image](https://user-images.githubusercontent.com/40603102/95031682-d0a8e700-06a6-11eb-90c5-69d7625d615b.png)

I hope you can guide me on how I could solve this problem.
Greetings

**Comment by phillbush** [comment]
It seems that the variables `lista` and `lista2` contain newlines, which makes `xnotify` produces more notifications than you wanted.

Try to replace the first two lines with the following:

```
lista=$(xbps-install -nuM | awk 'NR == 1 {printf "%s", $1}; NR > 1 {printf "; %s", $1}; END {print ""}')
lista2=$(xbps-install -nuM | awk 'NR == 1 {printf "%s", $1}; NR > 1 {printf "; %s", $1}; END {print ""}' | tail -n 12 )
```

This will make all the packages that needs update be listed in a single line (their newlines would be replaced by `; `).
Note that this will not make each package be listed on a single line, as `xnotify` does not have support for multiple lines (yet).

**Comment by tuxliban** [comment]
Great, I really appreciate your help. The solution you offered me was good.
Greetings

**Comment by phillbush** [comment]
> Great, I really appreciate your help. The solution you offered me was good.
> Greetings

You're welcome.

What that awk snipped does is: it reads the first line and prints its first field; then for each line after the first it prints their first field preceded by "`; `", and at the end, it prints a new line. (I think that the `END` part is optional, you can test it). I used the awk's `printf` command when I don't want a newline to be printed, and `print` when I want.

So rather than each package update precedes a newline, each update now precedes a semi-colon. Only the last update has a newline after it.
