### ISSUE TITLE
Feature request: Rouded corners and transparency

### ISSUE THREAD

**Issue by thenoobtester** [phillbush/xnotify#32]
Hi,

I love this, this is what libnotify's notify-send should be in my opinion. The only things from libnotify's notify-send that I would want here are the rounded corners and transparency. Do you think that that could be added?

Thank you again for this great piece of software.

**Comment by cdlscpmv** [comment]
You set opacity with a compositor like [picom](https://github.com/yshui/picom). Just add these lines to picom.conf:
```
opacity-rule = [
    "90:class_g = 'XNotify'"
]
```

**Comment by phillbush** [comment]
Transparency just implemented.
Picom could also do that, but it made everything transparent, including the text and image transparent, rather than only the background.

Rounded corners can be done with the compositor tho, so won't be implemented.
