### ISSUE TITLE
useless space appearing at end of message

### ISSUE THREAD

**Issue by wael444** [phillbush/xnotify#33]
```
printf 'why is this happening'| tr -d '\n' > /home/wael/.cache/xnotify:1.fifo
```
![image](https://user-images.githubusercontent.com/47404953/189474301-7a4f2470-308e-4ac9-a1e5-18794322136f.png)
```
00000000  77 68 79 20 69 73 20 74  68 69 73 20 68 61 70 70  |why is this happ|
00000010  65 6e 69 6e 67                                    |ening|
00000015
```
if there is no character after the end, why is there still a character?

**Comment by wael444** [comment]
it could be something with `.shrink` configuration option.

**Comment by phillbush** [comment]
The offending line was [xnotify.c:948](https://github.com/phillbush/xnotify/blob/58c7d5763c3fb1c32a76560c85d20a25f59d4687/xnotify.c#L948). I was adding the length of the ellipsis, appended long notification string that is broken to fit on the notification window. For short strings, the ellipsis is not necessary.

That line was a residue of the time I was testing line breaking with ellipsis.  
It's removed now.

PS: In this commit I also renamed the `xnotify*font` X resource to `xnotify*faceName`.  
`*font` should be used for the old [XLFD](https://wiki.archlinux.org/title/X_Logical_Font_Description) font description. Resources using the new xft font description should be called `*faceName`.
