### ISSUE TITLE
multiple lines feature

### ISSUE THREAD

**Issue by wael444** [phillbush/xnotify#34]
https://github.com/phillbush/xnotify/issues/3#issuecomment-703360816

> as xnotify does not have support for multiple lines (yet).

when?
i mean multiline parsing could be made by searching for simply the character `\n`

**Comment by phillbush** [comment]
Sorry for the late response, I totally forgot it.

I have implemented line breaking in some commit, it is done by additional tab-delimited fields:

```
printf 'Hello\tWorld\t!\n' | xnotify
```
