### ISSUE TITLE
Replace pipe mechanism with plain X11 properties?

### ISSUE THREAD

**Issue by phillbush** [phillbush/xnotify#37]
The way xnotify works now requires the user to set up a named pipe in order to reuse the same xnotify process and stack notifications one upon the other.

Setting up this mechanism is the one thing most people have problem with `xnotify`, especially those who have never worked with shell scripting or named pipes before.

An alternative to that would be doing like how Suckless' `dwm(1)` does with its status bar: write the notification into the title of the root window (or into any other property).

If this mechanism were adopted, there would be no need for `poll(2)`ing both the standard input and the X11 connection, for everything would be handled by X itself, simplifying much of the code. That would, however, require manual intervention for people who already use `xnotify`, and [break some workflows](
https://xkcd.com/1172/).

I'm leaving this issue here open for users to discuss whether dwm's approach should be adopted.

**Comment by wael444** [comment]
How would this even be implemented? will `xnotify` export an X atom that can be written to via a client program or `xprop`? if so, how will multiple notifications be managed? they will have to go into some history buffer, which would require some sort of timeout?

a similar program to `xnotify` is [`herbe`](https://github.com/dudik/herbe), which can't manage multiple notifications but is one program that sends notification and then quits. alternatively, there is [`dunst`](https://github.com/dunst-project/dunst), which listens on D-Bus calls.

another solution is to have a client-daemon system, where the daemon is `xnotify`and a client sends information to a socket or fifo of the `xnotify` daemon; more or less this is the same system we have, just simplified for the end user. however, if something like that is implemented, then `xnotify` would be a clone of [`dnote`](https://github.com/kolunmi/dnote), a similar notification program with a client-daemon system, which is very similar to `xnotify` in terms of features.

**Comment by GanerCodes** [comment]
You def should as to embed notifications has a lot of additional overhead to check if xnotify already has process open
