### ISSUE TITLE
Feature: gap relative to screen border

### ISSUE THREAD

**Issue by adrianFD22** [phillbush/xnotify#42]
I do not remember if this was a feature in previous versions but it would great to be able to specify a padding between the screen border and the notification.

**Comment by phillbush** [comment]
Hi, it was implemented before with the `-g` command-line option and the `XNotify.geometry` X resource.
After refactoring the code, I forgot to re-implement that.

Commit 440f8d5 readds it.

For example, setting the gravity to `NE` geometry to `-64+10` would place the northeast corner of the notifications 64 pixels to the left and 10 pixels below the northeast corner of the monitor.

**Comment by adrianFD22** [comment]
Is it possible that is not configurable via Xresources? I am using xnotify.geometry in my .Xresources file but does not work. It works when using xnotify with the -g flag.

**Comment by phillbush** [comment]
Oh, sorry. I totally forgot to also commit the change on the resource. It should be working now.

**Comment by adrianFD22** [comment]
Now it works perfectly fine. Thank you so much!
