### ISSUE TITLE
CLI control

### ISSUE THREAD

**Issue by czaplicki** [phillbush/xnotify#5]
Hey, could you add a way to close/discard and click/activate a notification from the command line?
Would love to be able to interact with xnotify through CLI extended by sxhkd to use my keyboard.
Maybe add special notifications to do sed things? It would enable interactions from any language.
Otherwise pretty perfect program, love 'the unix way'.

**Comment by phillbush** [comment]
That's a good idea.
I'll make xnotify respond to SIGUSR1 by discarding all notifications and respond to SIGUSR2 by simulating the click with the action button.

**Comment by phillbush** [comment]
Done!  
With the last commit, you can do `pkill -USR1 xnotify` (or `killall -USR1 xnotify`) to send to xnotify the USR1 signal, which tells it to close all notifications.  
The `USR2` signal also close all notifications but prints the `CMD:` of the first notification to stdout.
