### ISSUE TITLE
Wrap text in long notifs

### ISSUE THREAD

**Issue by icyphox** [phillbush/xnotify#7]
Long notification text oftentimes exceeds the notification window; wrapping it into the next line would be ideal. Is this possible?

**Comment by phillbush** [comment]
That's possible but difficult, as xnotify(1) uses low-level libraries (xlib and xft) that do not do text wrapping directly.  
Implementing text wrapping is on my todo list, however.  
I will implement that as an Xresources option to control how and whether to wrap or to truncate lines.

**Comment by phillbush** [comment]
Done!

The last commits add an option `xnotify.wrap` to control whether to wrap text.

Those commits also add the option to specify multiple lines in the input.  
The following command will display a notification with tree lines, the first of which (the title) will be displayed on the font specified by `xnotify.title.font`.

```
$ printf 'IMG:shrek.png\tLine #1 (title)\tLine #2\tLine #3\n' > $XNOTIFY_FIFO
```

![scrotus](https://user-images.githubusercontent.com/63266536/101723509-52046780-3aa4-11eb-902c-95bd8a850e3b.png)
